version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE=/api/flask
    image: medichat:latest
    container_name: medichat
    restart: unless-stopped
    ports:
      - "3000:8080"
